version: "3"
services:
  arts041:
    image: darc
    hostname: arts041
    expose:
      - 61000
    networks:
      - arts
    volumes:
      - $HOME/darc/integration_test_docker/controller:/home/arts/.controller
      - $HOME/darc/integration_test_docker/controller:/opt/amber
      - $HOME/darc/integration_test_docker:/home/arts/darc/
      - /tank/data:/data

  arts001:
    image: darc
    hostname: arts001
    expose: 
      - 61000
    networks:
      - arts
    volumes:
      - $HOME/darc/integration_test_docker/controller:/home/arts/.controller
      - $HOME/darc/integration_test_docker/controller:/opt/amber
      - $HOME/darc/integration_test_docker:/home/arts/darc/
      - /tank/data:/data

networks:
  arts:
